### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/react-boilerplate#1]
# Motivation
We want to make a very minimal repository to be able to develop react apps.

# Tasks
- [x] Find someone else's boilerplate.
- [x] Adapt it to new package versions.
- [x] Add some of my own packages as necessary.
- [x] Be able to see the updates while developing.
